# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-30 17:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='year',
            name='start_date_of_signups',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date and time when signups are starting'),
        ),
    ]
