# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-11 12:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_scheduleevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='name',
            field=models.CharField(choices=[('lunch', 'Lunch'), ('dinner', 'Dinner')], default='lunch', max_length=127),
        ),
        migrations.AlterField(
            model_name='participant',
            name='email',
            field=models.EmailField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(max_length=127, unique=True, verbose_name='Team name'),
        ),
    ]
