# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-12 14:34
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0007_auto_20170312_1245'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='participant',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='participant',
            name='email',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='id',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='password',
        ),
        migrations.AddField(
            model_name='participant',
            name='user_ptr',
            field=models.OneToOneField(auto_created=True, default=None, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
