# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-12 22:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20170312_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reservation', to='api.Order', verbose_name='Order'),
        ),
    ]
