# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-12 23:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20170312_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='canceled',
            field=models.BooleanField(default=False, verbose_name='Is canceled?'),
        ),
    ]
