# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-13 13:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20170312_2348'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('in_progress', 'In progress'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], default='in_progress', max_length=255),
        ),
        migrations.AlterField(
            model_name='order',
            name='symvar',
            field=models.CharField(blank=True, max_length=63, unique=True, verbose_name='Variable symbol'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='symvar',
            field=models.CharField(blank=True, help_text='Variable symbol of the transaction', max_length=255, unique=True, verbose_name='Variable symbol'),
        ),
    ]
