# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-13 23:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20170313_1826'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='year',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='meals', to='api.Year'),
            preserve_default=False,
        ),
    ]
