# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-14 01:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_meal_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abstractfood',
            name='visibility',
            field=models.PositiveIntegerField(choices=[(1, 'Private'), (2, 'Public'), (3, 'Deleted')], default=2),
        ),
        migrations.AlterField(
            model_name='accomodation',
            name='visibility',
            field=models.PositiveIntegerField(choices=[(1, 'Private'), (2, 'Public'), (3, 'Deleted')], default=2),
        ),
        migrations.AlterField(
            model_name='accomodationphoto',
            name='visibility',
            field=models.PositiveIntegerField(choices=[(1, 'Private'), (2, 'Public'), (3, 'Deleted')], default=2),
        ),
        migrations.AlterField(
            model_name='foodphoto',
            name='visibility',
            field=models.PositiveIntegerField(choices=[(1, 'Private'), (2, 'Public'), (3, 'Deleted')], default=2),
        ),
        migrations.AlterField(
            model_name='lectorphoto',
            name='visibility',
            field=models.PositiveIntegerField(choices=[(1, 'Private'), (2, 'Public'), (3, 'Deleted')], default=2),
        ),
        migrations.AlterField(
            model_name='meal',
            name='visibility',
            field=models.PositiveIntegerField(choices=[(1, 'Private'), (2, 'Public'), (3, 'Deleted')], default=2),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='visibility',
            field=models.PositiveIntegerField(choices=[(1, 'Private'), (2, 'Public'), (3, 'Deleted')], default=2),
        ),
        migrations.AlterField(
            model_name='workshopphoto',
            name='visibility',
            field=models.PositiveIntegerField(choices=[(1, 'Private'), (2, 'Public'), (3, 'Deleted')], default=2),
        ),
    ]
