# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-15 19:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_order_confirmed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='paid',
        ),
        migrations.AlterField(
            model_name='payment',
            name='order',
            field=models.ForeignKey(blank=True, help_text='Which order is this payment related to?', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='api.Order', verbose_name='Order'),
        ),
    ]
