# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-15 21:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20170315_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='symvar',
            field=models.CharField(blank=True, help_text='Variable symbol of the transaction', max_length=255, verbose_name='Variable symbol'),
        ),
    ]
