# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-15 23:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20170315_2124'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='user_identification',
            field=models.CharField(max_length=255, null=True, verbose_name='User identification given by the bank'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='message',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='Message'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='symcon',
            field=models.CharField(blank=True, help_text='Constant symbol of the transaction', max_length=255, null=True, verbose_name='Constant symbol'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='symspc',
            field=models.CharField(blank=True, help_text='Specific symbol of the transaction', max_length=255, null=True, verbose_name='Specific symbol'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='symvar',
            field=models.CharField(blank=True, help_text='Variable symbol of the transaction', max_length=255, null=True, verbose_name='Variable symbol'),
        ),
    ]
