# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-18 16:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_auto_20170315_2342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='user_identification',
            field=models.CharField(help_text='User identification given by the bank', max_length=255, null=True, verbose_name='User identification'),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(blank=True, max_length=127, unique=True, verbose_name='Team name'),
        ),
    ]
