# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-22 12:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_auto_20170318_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='bank',
            field=models.CharField(blank=True, default='unknown', help_text='Bank sending this payment', max_length=255, verbose_name='Bank'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='currency',
            field=models.CharField(blank=True, default='unknown', help_text='Currency of the payment', max_length=255, verbose_name='Currency'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='sender',
            field=models.CharField(blank=True, default='unknown', help_text='Account number of person sending this payment', max_length=255, verbose_name='Sender'),
        ),
    ]
