# Generated by Django 2.0.1 on 2018-01-31 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_year_end_food_picking_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealreservation',
            name='food',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.Food', verbose_name='Food'),
        ),
        migrations.AlterField(
            model_name='mealreservation',
            name='meal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.Meal', verbose_name='Meal'),
        ),
        migrations.AlterField(
            model_name='mealreservation',
            name='soup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.Soup', verbose_name='Soup'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='assigned_workshop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.Workshop'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.Team', verbose_name='Team'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='accomodation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.Accomodation', verbose_name='Accomodation'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='workshop_price',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.WorkshopPrice', verbose_name='Workshop price'),
        ),
        migrations.AlterField(
            model_name='scheduleevent',
            name='performer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='events', to='api_textual.Performer'),
        ),
        migrations.AlterField(
            model_name='scheduleevent',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='api.Year', verbose_name='Year'),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='difficulty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.WorkshopDifficulty', verbose_name='Difficulty'),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api_textual.WorkshopLocation', verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='workshoplector',
            name='lector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.Lector', verbose_name='Lector'),
        ),
        migrations.AlterField(
            model_name='workshoplector',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.LectorRole', verbose_name='Lector role'),
        ),
        migrations.AlterField(
            model_name='workshopprice',
            name='price_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='workshop_prices', to='api.PriceLevel', verbose_name='Price level'),
        ),
    ]
