# Generated by Django 2.0.1 on 2018-02-01 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_auto_20180131_0752'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParticipantWorkshop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Participant')),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.Workshop')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
