# Generated by Django 2.0.2 on 2018-03-08 22:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_accomodationdescription_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='year',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='api.Year'),
        ),
    ]
