# Generated by Django 2.0.2 on 2018-03-09 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_order_year_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='accomodation',
            name='year',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='api.Year'),
        ),
    ]
