# Generated by Django 2.0.2 on 2018-03-11 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_accomodation_year_data'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='year',
            options={'ordering': ('-year',)},
        ),
        migrations.AddField(
            model_name='workshop',
            name='year',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='workshops', to='api.Year'),
        ),
    ]
