# Generated by Django 2.0.2 on 2018-03-12 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_auto_20180311_1609'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AddField(
            model_name='pricelevel',
            name='entryFee',
            field=models.PositiveIntegerField(blank=True, default=None, null=True, verbose_name='Nightly fee'),
        ),
    ]
