# Generated by Django 2.0.2 on 2018-03-13 02:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_auto_20180312_2322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participantworkshop',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workshops', to='api.Participant'),
        ),
        migrations.AlterField(
            model_name='participantworkshop',
            name='workshop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='participants', to='api.Workshop'),
        ),
    ]
