# Generated by Django 2.0.2 on 2018-03-13 02:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_auto_20180313_0205'),
    ]

    operations = [
        migrations.AddField(
            model_name='participantworkshop',
            name='year',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='api.Year'),
        ),
    ]
