# Generated by Django 2.0.2 on 2018-03-14 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_participantstay'),
    ]

    operations = [
        migrations.AddField(
            model_name='participantstay',
            name='year',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.Year', verbose_name='Year'),
            preserve_default=False,
        ),
    ]
