# Generated by Django 2.0.2 on 2018-05-02 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_auto_20180319_1903'),
    ]

    operations = [
        migrations.AddField(
            model_name='accomodation',
            name='requires_identification',
            field=models.BooleanField(default=False, help_text='This accomodation requires to know persons home address and ID number', verbose_name='Requires Identification'),
        ),
        migrations.AlterField(
            model_name='participantstay',
            name='date',
            field=models.DateField(help_text='Does the participant accepted the rules of the festival?', verbose_name='Are rules accepted?'),
        ),
        migrations.AlterField(
            model_name='participantstay',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stay', to='api.Participant', verbose_name='Participant'),
        ),
        migrations.AlterField(
            model_name='participantstay',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stay', to='api.Year', verbose_name='Year'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='workshop_price',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.WorkshopPrice', verbose_name='Workshop price'),
        ),
    ]
