# Generated by Django 2.0.2 on 2018-05-02 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_auto_20180319_1903'),
    ]

    operations = [
        migrations.AddField(
            model_name='accomodation',
            name='requires_identification',
            field=models.BooleanField(default=False, help_text='This accomodation requires to know persons home address and ID number', verbose_name='Requires Identification'),
        ),
    ]
