# Generated by Django 2.0.2 on 2018-05-02 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_auto_20180502_2122'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='id_number',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ID Number'),
        ),
    ]
