# Generated by Django 2.0.2 on 2018-05-02 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0042_participant_id_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='accomodation',
            name='address',
            field=models.CharField(blank=True, help_text='Full physical address of the accomodation', max_length=255, null=True, verbose_name='Accomodation address'),
        ),
    ]
