# Generated by Django 2.0.2 on 2018-05-03 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_accomodation_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleevent',
            name='location_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Location Name'),
        ),
    ]
