# Generated by Django 2.0.5 on 2018-05-07 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0045_auto_20180504_0008'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='participant',
            managers=[
            ],
        ),
    ]
