# Generated by Django 2.1.7 on 2019-03-17 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0046_auto_20180507_1803'),
    ]

    operations = [
        migrations.AddField(
            model_name='year',
            name='without_workshop',
            field=models.BooleanField(default=True, verbose_name='Can people attend festival without workshop?'),
        ),
    ]
