# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-01 16:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_textual', '0002_news'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='var/photos')),
                ('desc', models.CharField(blank=True, max_length=255, null=True, verbose_name='Description')),
                ('visibility', models.PositiveIntegerField(choices=[(1, 'Private'), (2, 'Public'), (3, 'Deleted')])),
                ('text', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='api_textual.News', verbose_name='News')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
