# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-09 22:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_textual', '0003_newsphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsphoto',
            name='height',
            field=models.PositiveIntegerField(blank=True, default=100, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='newsphoto',
            name='width',
            field=models.PositiveIntegerField(blank=True, default=100, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='textphoto',
            name='height',
            field=models.PositiveIntegerField(blank=True, default=100, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='textphoto',
            name='width',
            field=models.PositiveIntegerField(blank=True, default=100, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='travelingtipphoto',
            name='height',
            field=models.PositiveIntegerField(blank=True, default=100, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='travelingtipphoto',
            name='width',
            field=models.PositiveIntegerField(blank=True, default=100, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='workshoplocationphoto',
            name='height',
            field=models.PositiveIntegerField(blank=True, default=100, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='workshoplocationphoto',
            name='width',
            field=models.PositiveIntegerField(blank=True, default=100, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='newsphoto',
            name='image',
            field=models.ImageField(height_field='height', upload_to='var/photos', width_field='width'),
        ),
        migrations.AlterField(
            model_name='textphoto',
            name='image',
            field=models.ImageField(height_field='height', upload_to='var/photos', width_field='width'),
        ),
        migrations.AlterField(
            model_name='travelingtipphoto',
            name='image',
            field=models.ImageField(height_field='height', upload_to='var/photos', width_field='width'),
        ),
        migrations.AlterField(
            model_name='workshoplocationphoto',
            name='image',
            field=models.ImageField(height_field='height', upload_to='var/photos', width_field='width'),
        ),
    ]
