# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-14 01:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_textual', '0005_performer_performerphoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsphoto',
            name='visibility',
            field=models.PositiveIntegerField(choices=[(1, 'Private'), (2, 'Public'), (3, 'Deleted')], default=2),
        ),
        migrations.AlterField(
            model_name='performerphoto',
            name='visibility',
            field=models.PositiveIntegerField(choices=[(1, 'Private'), (2, 'Public'), (3, 'Deleted')], default=2),
        ),
        migrations.AlterField(
            model_name='textphoto',
            name='visibility',
            field=models.PositiveIntegerField(choices=[(1, 'Private'), (2, 'Public'), (3, 'Deleted')], default=2),
        ),
        migrations.AlterField(
            model_name='travelingtipphoto',
            name='visibility',
            field=models.PositiveIntegerField(choices=[(1, 'Private'), (2, 'Public'), (3, 'Deleted')], default=2),
        ),
        migrations.AlterField(
            model_name='workshoplocationphoto',
            name='visibility',
            field=models.PositiveIntegerField(choices=[(1, 'Private'), (2, 'Public'), (3, 'Deleted')], default=2),
        ),
    ]
