# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-21 18:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_textual', '0006_auto_20170314_0120'),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='eg. Fish and chips', max_length=127, verbose_name='Name')),
                ('service', models.CharField(blank=True, choices=[('bandzone', 'Bandzone'), ('facebook', 'Facebook'), ('soundcloud', 'Soundcloud'), ('youtube', 'YouTube')], max_length=63, null=True, verbose_name='Linked service')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question', models.CharField(max_length=255, verbose_name='Poll question, for example What is the capital         of Czech republic')),
                ('closed', models.BooleanField(default=False, verbose_name='Poll is closed')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PollAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('text', models.CharField(max_length=255, verbose_name='Answer')),
                ('performer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='polls', to='api_textual.Performer')),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='api_textual.Poll')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PollVote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='api_textual.PollAnswer')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='news',
            name='poll',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api_textual.Poll'),
        ),
        migrations.AddField(
            model_name='performer',
            name='links',
            field=models.ManyToManyField(related_name='performers', to='api_textual.Link'),
        ),
    ]
