# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-21 22:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_textual', '0008_auto_20170321_1817'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerformerLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='eg. Fish and chips', max_length=127, verbose_name='Name')),
                ('service', models.CharField(blank=True, choices=[('bandzone', 'Bandzone'), ('facebook', 'Facebook'), ('soundcloud', 'SoundCloud'), ('youtube', 'YouTube')], max_length=63, null=True, verbose_name='Linked service')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='performer',
            name='links',
        ),
        migrations.AlterField(
            model_name='poll',
            name='question',
            field=models.CharField(help_text='For example What is the capital of Czech republic', max_length=255, verbose_name='Poll question'),
        ),
        migrations.AlterField(
            model_name='pollvote',
            name='answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='api_textual.PollAnswer'),
        ),
        migrations.DeleteModel(
            name='Link',
        ),
        migrations.AddField(
            model_name='performerlink',
            name='performer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='api_textual.Performer'),
        ),
    ]
