# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-21 23:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_textual', '0009_auto_20170321_2222'),
    ]

    operations = [
        migrations.AddField(
            model_name='performerlink',
            name='address',
            field=models.URLField(default=None, max_length=255, verbose_name='URL'),
            preserve_default=False,
        ),
    ]
