# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-26 22:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_textual', '0010_performerlink_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='pollvote',
            name='remote_addr',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
