# Generated by Django 2.0.1 on 2018-01-31 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_textual', '0011_pollvote_remote_addr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='poll',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api_textual.Poll'),
        ),
    ]
