# Generated by Django 2.0.1 on 2018-03-06 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_textual', '0012_auto_20180131_0752'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='lang',
            field=models.CharField(choices=[('cs', 'Česky'), ('en', 'English')], default='cs', max_length=16, verbose_name='Language'),
        ),
        migrations.AddField(
            model_name='performer',
            name='lang',
            field=models.CharField(choices=[('cs', 'Česky'), ('en', 'English')], default='cs', max_length=16, verbose_name='Language'),
        ),
        migrations.AddField(
            model_name='text',
            name='lang',
            field=models.CharField(choices=[('cs', 'Česky'), ('en', 'English')], default='cs', max_length=16, verbose_name='Language'),
        ),
        migrations.AddField(
            model_name='travelingtip',
            name='lang',
            field=models.CharField(choices=[('cs', 'Česky'), ('en', 'English')], default='cs', max_length=16, verbose_name='Language'),
        ),
        migrations.AddField(
            model_name='workshoplocation',
            name='lang',
            field=models.CharField(choices=[('cs', 'Česky'), ('en', 'English')], default='cs', max_length=16, verbose_name='Language'),
        ),
    ]
