# Generated by Django 2.0.1 on 2018-03-06 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_textual', '0013_auto_20180306_0747'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerformerDescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=127, verbose_name='Name')),
                ('slug', models.SlugField(verbose_name='Identifier in URL')),
                ('text', models.TextField(verbose_name='Text')),
                ('lang', models.CharField(choices=[('cs', 'Česky'), ('en', 'English')], default='cs', max_length=16, verbose_name='Language')),
            ],
            options={
                'verbose_name': 'Performer',
                'verbose_name_plural': 'Performers',
            },
        ),
        migrations.RemoveField(
            model_name='performer',
            name='lang',
        ),
        migrations.AddField(
            model_name='performerdescription',
            name='performer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='descriptions', to='api_textual.Performer', verbose_name='Performer'),
        ),
    ]
