# Generated by Django 2.0.1 on 2018-03-06 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_textual', '0016_remove_performer_text'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='performerdescription',
            options={'verbose_name': 'Performer Description', 'verbose_name_plural': 'Performer Descriptions'},
        ),
        migrations.RemoveField(
            model_name='performerdescription',
            name='name',
        ),
        migrations.RemoveField(
            model_name='performerdescription',
            name='slug',
        ),
    ]
