# Generated by Django 2.0.1 on 2018-03-06 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_textual', '0017_auto_20180306_0808'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkshopLocationDescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('text', models.TextField(verbose_name='Text')),
                ('lang', models.CharField(choices=[('cs', 'Česky'), ('en', 'English')], default='cs', max_length=16, verbose_name='Language')),
                ('performer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='descriptions', to='api_textual.WorkshopLocation', verbose_name='WorkshopLocation')),
            ],
            options={
                'verbose_name': 'Workshop Location Description',
                'verbose_name_plural': 'Workshop Location Descriptions',
            },
        ),
    ]
