# Generated by Django 2.0.1 on 2018-03-06 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_textual', '0019_workshop_location_texts_20180306_0913'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workshoplocation',
            name='lang',
        ),
        migrations.RemoveField(
            model_name='workshoplocation',
            name='text',
        ),
    ]
