# Generated by Django 2.0.2 on 2018-03-06 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_textual', '0020_auto_20180306_0817'),
    ]

    operations = [
        migrations.AddField(
            model_name='text',
            name='category',
            field=models.CharField(choices=[('home', 'homepage'), ('accomodation', 'accomodation'), ('fees', 'fees'), ('food', 'food'), ('locations', 'locations'), ('schedule', 'schedule')], max_length=127, null=True, verbose_name='Category'),
        ),
    ]
