# Generated by Django 2.0.2 on 2018-05-04 00:09

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0045_auto_20180504_0008'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inhabitant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inhabited_rooms', to='api.Participant', verbose_name='Participant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(max_length=255, verbose_name='Room Number')),
                ('size', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Size')),
                ('accomodation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='api.Accomodation')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='inhabitant',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inhabitants', to='api_roommates.Room', verbose_name='Room'),
        ),
    ]
