VISIBILITY_PRIVATE = 1
VISIBILITY_PUBLIC = 2
VISIBILITY_DELETED = 3

VISIBILITY_CHOICES = (
    (VISIBILITY_PRIVATE, 'Private'),
    (VISIBILITY_PUBLIC, 'Public'),
    (VISIBILITY_DELETED, 'Deleted'),
)
